### ISSUE TITLE
Design Considerations

### ISSUE THREAD

**Issue by Xplorer001** [ExploreEmbedded/FunTime#1]
- [ ] Bigger segments(1.2 inch ?) will aid better visibility. If not readily available we can go with .56 inch ones. 
- [ ] Ideas for Acrylic Cases. 
- [ ] Test driving circuit for .5W led, that acts as night lamp

**Comment by raghavendrahassy** [comment]
0.5W straw hat LED driving circuit. 

![image](https://cloud.githubusercontent.com/assets/12540595/19034138/9326906a-897f-11e6-9f93-96631fe1f1c2.png)

**Comment by raghavendrahassy** [comment]
Bigger segments(1.2 inch ?) will aid better visibility. If not readily available we can go with .56 inch ones.
This can be implemented in the next the revision.
 Ideas for Acrylic Cases.
Done
 Test driving circuit for .5W led, that acts as night lamp
Designed using BD139 Transistor
