### ISSUE TITLE
Pin Assigments

### ISSUE THREAD

**Issue by Xplorer001** [ExploreEmbedded/FunTime#2]
- Change **SET** PIN to Arduino **PIN 2** (PORTD2) for using interrupt to walk from sleep and check time.
- Change **A** to Arduino **PIN 4** 
- Set Value of R1 TO 100K and R2 to 10K
- Add zener diode of 5.1v break down across dc adapter input.

**Comment by raghavendrahassy** [comment]
Changes has been done
